version: '3.5'

services:
  github-deploy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - ROLLBAR_TOKEN=${ROLLBAR_TOKEN}
      - KUBECONFIG=${KUBECONFIG}
      - DOCKER_HOST=${DOCKER_HOST}
    volumes:
      - ${MY_KUBECONFIG}:/root/.kube/config 
      # - ./internal/config/config.yaml:/app/internal/config/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    networks:
      - github-deploy-network

networks:
  github-deploy-network:
    driver: bridge  # Explicitly define the driver if necessary
