apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-kube-auto-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-kube-auto-deploy
  template:
    metadata:
      labels:
        app: webhook-kube-auto-deploy
    spec:
      serviceAccountName: webhook-kube-auto-deploy # Specifies the service account for the pod.
      containers:
      - name: webhook-kube-auto-deploy
        image: ghcr.io/uib-ub/uib-ub/hono-kube-deploy-automation:latest
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8080
        env:
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        - name: DOCKER_BUILDKIT
          value: "1" # enable BuildKit for building docker images efficiently.
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-cred
              key: github-token
              optional: false
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: webhook-cred
              key: webhook-secret
              optional: false
        - name: ROLLBAR_TOKEN
          valueFrom:
            secretKeyRef:
              name: rollbar-cred
              key: rollbar-token
              optional: false
        securityContext:
          privileged: true # Required for Docker-in-Docker unless using socket mounting
          readOnlyRootFilesystem: false # Set to true if your app does not need to write to the filesystem
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: docker-sock
          mountPath: /var/run/docker.sock
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 5
      imagePullSecrets:
      - name: github-deploy-regcred # Refers to a secret (github-deploy-regcred) to authenticate with the container registry for pulling images.
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-kube-auto-deploy
spec:
  type: ClusterIP
  ports:
  - name: webhook-kube-auto-deploy-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webhook-kube-auto-deploy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-kube-auto-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-kube-auto-deploy
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"] # Permissions to check pod status
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["namespaces", "services", "configmaps", "deployments", "ingresses", "pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-kube-auto-deploy
subjects:
- kind: ServiceAccount
  name: webhook-kube-auto-deploy
  namespace: default
roleRef:
  kind: ClusterRole
  name: webhook-kube-auto-deploy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-git-deploy-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - api-git-deploy.testdu.uib.no
    secretName: api-git-deploy-ingress-tls
  rules:
  - host: api-git-deploy.testdu.uib.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webhook-kube-auto-deploy
            port:
              number: 80

