github:
  workflowPrefix: "deploy-kube-secrets"
  localRepo: "app"
  packageType: "container"
  prDeployLabel: "deploy-test-hono"

kubernetes:
  resource: "k8s-hono-api"
  devNamespace: "hono-api-dev"
  testNamespace: "hono-api-test"

container:
  dockerFile: "Dockerfile.api"
  registry: "ghcr.io"
  imageSuffix: "api"
