github:
  workflowPrefix: "deploy-kube-secrets"
  localRepo: "app"

kubernetes:
  resource: "microk8s-hono-api"
  devNamespace: "hono-api-dev"
  testNamespace: "hono-api-test"

container:
  dockerFile: "Dockerfile.api"
  registry: "ghcr.io"
  imageSuffix: "api"

  
