name: Testing GO code

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

  pull_request:
    branches:
      - main # Trigger on PRs targeting main only
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run tests
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.event.pull_request.merged == false)
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
        ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
        LOCAL_REPO_SRC: ${{ runner.home }}/app
      run: |
        go test -v ./internal/...
